site_name: hikari-wave
site_url: https://hikari-wave.wildevstudios.net
copyright: Copyright &copy; 2025 WilDev Studios. This software is protected by copyright and licensed under the MIT license.

repo_url: https://github.com/WilDev-Studios/hikari-wave

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo-padded.png
  palette:
    - scheme: slate
      primary: pink
      accent: orange
  font:
    text: Monospace
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - redirects
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3.10/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
          paths: ["."]
          options:
            heading_level: 3
            annotations_path: source
            docstring_style: numpy
            docstring_section_style: spacy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            extra:
              show_toc: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WilDev-Studios/hikari-wave
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4Ggybyy87d

nav:
  - Home: index.md
  - API Reference:
    - Audio:
      - FFmpeg: pages/api/audio/ffmpeg.md
      - Player: pages/api/audio/player.md
      - Source: pages/api/audio/source.md
    - Client: pages/api/client.md
    - Connection: pages/api/connection.md
    - Event:
      - Events: pages/api/event/events.md
      - Factory: pages/api/event/factory.md
      - Types: pages/api/event/types.md
    - Internal:
      - Constants: pages/api/internal/constants.md
      - Encrypt: pages/api/internal/encrypt.md
      - Error: pages/api/internal/error.md
      - Result: pages/api/internal/result.md
    - Networking:
      - Gateway: pages/api/networking/gateway.md
      - Server: pages/api/networking/server.md
  - Changelog:
    - Index: pages/changelog/index.md
    - 0.0.1a5 (STAGING): pages/changelog/0.0.1a5.md
    - 0.0.1a4 (12-19-2025): pages/changelog/0.0.1a4.md
    - 0.0.1a3 (12-17-2025): pages/changelog/0.0.1a3.md
    - 0.0.1a2 (12-17-2025): pages/changelog/0.0.1a2.md
    - 0.0.1a1 (12-16-2025): pages/changelog/0.0.1a1.md